"""add consultations table

Revision ID: 2763f0156e3b
Revises: 691a40698b1b
Create Date: 2026-07-19 02:01:11.802129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2763f0156e3b'
down_revision: Union[str, Sequence[str], None] = '691a40698b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('recording_consent', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('processing_status', sa.Enum('pending', 'transcribing', 'summarizing', 'ready', 'failed', name='processing_status'), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('ai_summary_draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_appointment_id'), 'consultations', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_consultations_hospital_id'), 'consultations', ['hospital_id'], unique=False)
    # ### end Alembic commands ###

    # Row-Level Security tenant isolation (autogenerate cannot detect this).
    op.execute("ALTER TABLE consultations ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE consultations FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON consultations
        USING (
            hospital_id = current_setting('app.current_hospital_id', true)::uuid
        )
        WITH CHECK (
            hospital_id = current_setting('app.current_hospital_id', true)::uuid
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON consultations")
    op.drop_index(op.f('ix_consultations_hospital_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_appointment_id'), table_name='consultations')
    op.drop_table('consultations')
    op.execute("DROP TYPE IF EXISTS processing_status")
    # ### end Alembic commands ###
