"""add doctor sessions and appointment paid

Revision ID: bcdef3d087e8
Revises: 2763f0156e3b
Create Date: 2026-07-19 17:01:42.508117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcdef3d087e8'
down_revision: Union[str, Sequence[str], None] = '2763f0156e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('paid', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('doctors', sa.Column('sessions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'sessions')
    op.drop_column('appointments', 'paid')
    # ### end Alembic commands ###
